version: '2'

services:
    nginx:
        image: nginx:1.19
        restart: always
        volumes:
            - .:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/templates
        depends_on:
            - php
        links:
            - php
        ports:
            - "${COMPOSE_NGINX_PORT}:80"
        networks:
            - raffle_prizes_test
    php:
        build:
            context: ./docker/images/php
        restart: always
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./docker/cron:/etc/cron.d
        links:
            - mysql
            - redis
        networks:
            - raffle_prizes_test
    mysql:
        image: mysql:8
        restart: always
        volumes:
            - ./docker/db/mysql/dump:/docker-entrypoint-initdb.d
            - ./docker/db/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/alternatives/my.cnf
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        ports:
            - "${COMPOSE_MYSQL_PORT}:3306"
        networks:
            - raffle_prizes_test
    redis:
        image: redis:alpine
        restart: always
        ports:
            - "${COMPOSE_REDIS_PORT}:6379"
        volumes:
            - ./docker/db/redis:/data
        networks:
            - raffle_prizes_test
networks:
    raffle_prizes_test:
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: 192.168.100.0/25
